In [2]:
import numpy as np

In [7]:
"""1: 
Write a function so that the columns of the output matrix are powers of the input vector. 

The order of the powers is determined by the increasing boolean argument. Specifically, 
when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.
"""

'1: \nWrite a function so that the columns of the output matrix are powers of the input vector. \n\nThe order of the powers is determined by the increasing boolean argument. Specifically, \nwhen increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. \nHINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.\n'

In [8]:
def matrix_powers(vector, n, increasing):
    pass
    if increasing==True:
        return np.array([i**j for i in vector for j in range(n)]).reshape(len(vector), n)
    else:
        return np.array([i**(n-1-j) for i in vector for j in range(n)]).reshape(vector.size, n)
        
    


l=np.array([1,2,3,4,5,7])
a=matrix_powers(l, 3, True)
print(a)
print()
print()
b=matrix_powers(l, 3, False)
print(b)

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]
 [ 1  7 49]]


[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]
 [49  7  1]]


In [9]:
"""
2: 
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence
is defined as follows: 
The moving average sequence has n-k+1 elements as shown below. 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
i 1 2 3 4 5 6 7 8 9 10 ===== == == == == == == == == == == Input 10 20 30 40 50 60 70 80 90 100 
y1 25 = (10+20+30+40)/4 
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4 
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4 
y6 75 = (60+70+80+90)/4 
y7 85 = (70+80+90+100)/4 
Thus, the moving average sequence has n-k+1=10-4+1=7 values. 
Question: Write a function to find moving average in an array over a window: 
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

"""

'\n2: \nGiven a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence\nis defined as follows: \nThe moving average sequence has n-k+1 elements as shown below. \nThe moving averages with k=4 of a ten-value sequence (n=10) is shown below \ni 1 2 3 4 5 6 7 8 9 10 ===== == == == == == == == == == == Input 10 20 30 40 50 60 70 80 90 100 \ny1 25 = (10+20+30+40)/4 \ny2 35 = (20+30+40+50)/4\ny3 45 = (30+40+50+60)/4 \ny4 55 = (40+50+60+70)/4\ny5 65 = (50+60+70+80)/4 \ny6 75 = (60+70+80+90)/4 \ny7 85 = (70+80+90+100)/4 \nThus, the moving average sequence has n-k+1=10-4+1=7 values. \nQuestion: Write a function to find moving average in an array over a window: \nTest it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. \n\n'

In [10]:
#
import math
arr=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3
n=len(arr)
#n-k+1=> 13-3+1=11
total_gen=n-k+1
total_gen
for i in range(total_gen):
    #print(i)
    sum=0
    s=''
    for j in range(i,i+k):
        sum=sum+arr[j]
        s=s+'+'+str(arr[j])
    print(s+'/3=',sum/3)
    print()
    

+3+5+7/3= 5.0

+5+7+2/3= 4.666666666666667

+7+2+8/3= 5.666666666666667

+2+8+10/3= 6.666666666666667

+8+10+11/3= 9.666666666666666

+10+11+65/3= 28.666666666666668

+11+65+72/3= 49.333333333333336

+65+72+81/3= 72.66666666666667

+72+81+99/3= 84.0

+81+99+100/3= 93.33333333333333

+99+100+150/3= 116.33333333333333

